<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="FluentValidation" Version="12.1.1" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.0" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="NServiceBus" Version="10.2.7" />
    <PackageVersion Include="NServiceBus.AmazonSQS" Version="9.1.1" />
    <PackageVersion Include="NServiceBus.Extensions.Hosting" Version="4.1.0" />
    <PackageVersion Include="NServiceBus.Heartbeat" Version="6.0.1" />
    <PackageVersion Include="NServiceBus.RabbitMQ" Version="11.2.1" />
    <PackageVersion Include="NServiceBus.Transport.AzureServiceBus" Version="6.4.2" />
    <PackageVersion Include="NServiceBus.Transport.AzureStorageQueues" Version="14.1.0" />
    <PackageVersion Include="NServiceBus.Transport.PostgreSql" Version="9.1.0" />
    <PackageVersion Include="NServiceBus.Transport.SqlServer" Version="9.1.0" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.14.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageVersion Include="Spectre.Console.Cli.Extensions.DependencyInjection" Version="0.27.0" />
    <PackageVersion Include="Spectre.Console.Cli.Testing" Version="1.0.0-alpha.0.16" />
    <PackageVersion Include="Testcontainers.Azurite" Version="4.13.0" />
    <PackageVersion Include="Testcontainers.LocalStack" Version="4.13.0" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.13.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageVersion Include="Testcontainers.RabbitMq" Version="4.13.0" />
    <PackageVersion Include="Testcontainers.ServiceBus" Version="4.13.0" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>