<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <RootNamespace>BuslyCLI</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <!-- Dotnet tool packageid in nuget -->
    <PackageId>dotnet-busly</PackageId>
    <ToolCommandName>dotnet-busly</ToolCommandName>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>busly-logo-128x128.png</PackageIcon>
    <RepositoryUrl>https://github.com/TraGicCode/busly-cli</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <InformationalVersion>0.1.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <AssemblyName>busly</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
    <None Include="..\..\website\static\img\busly-logo-128x128.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
    <PackageReference Include="NServiceBus" Version="10.1.4" />
    <PackageReference Include="NServiceBus.AmazonSQS" Version="9.0.1" />
    <PackageReference Include="NServiceBus.RabbitMQ" Version="11.2.1" />
    <PackageReference Include="NServiceBus.Transport.AzureServiceBus" Version="6.3.0" />
    <PackageReference Include="NServiceBus.Transport.AzureStorageQueues" Version="14.0.1" />
    <PackageReference Include="NServiceBus.Transport.PostgreSql" Version="9.0.1" />
    <PackageReference Include="NServiceBus.Transport.SqlServer" Version="9.0.1" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageReference Include="Spectre.Console.Cli.Extensions.DependencyInjection" Version="0.24.0" />
    <PackageReference Include="YamlDotNet" Version="17.1.0" />
  </ItemGroup>

</Project>
