<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>BuslyCLI.Console.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NServiceBus.AmazonSQS" />
    <PackageReference Include="NServiceBus.Extensions.Hosting" />
    <PackageReference Include="NServiceBus.Heartbeat" />
    <PackageReference Include="NServiceBus.RabbitMQ" />
    <PackageReference Include="NServiceBus.Transport.AzureServiceBus" />
    <PackageReference Include="NServiceBus.Transport.AzureStorageQueues" />
    <PackageReference Include="NServiceBus.Transport.PostgreSql" />
    <PackageReference Include="NServiceBus.Transport.SqlServer" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Spectre.Console.Cli.Testing" />
    <PackageReference Include="Testcontainers.Azurite" />
    <PackageReference Include="Testcontainers.LocalStack" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="Testcontainers.ServiceBus" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuslyCLI.Console\BuslyCLI.Console.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\ServiceControl\Endpoint\" />
    <Folder Include="Commands\ServiceControl\License\" />
  </ItemGroup>

</Project>
