name: Build and Publish Docker Image

on:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  docker:
    needs: version
    uses: ./.github/workflows/docker-build-or-deploy.yml
    #    permissions:
    #      contents: read
    #      id-token: write
    #      attestations: write
    with:
      push: true
      version: ${{ needs.version.outputs.version }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}