name: Build and Publish .NET Tool

on:
  release:
    types: [published]

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get semver without "v"
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build and Pack as .NET tool
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
             dotnet cake --target Pack-DotNetTool --package-version ${{ steps.version.outputs.VERSION }}

      - name: Publish to NuGet (optional)
        run: dotnet nuget push ./artifacts/nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
