name: Build and Publish .NET Tool

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string


jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build and Pack as .NET tool
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
             dotnet cake --target Pack-DotNetTool --package-version ${{ inputs.version }}

      - name: Publish to NuGet (optional)
        run: dotnet nuget push ./artifacts/nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
