name: Publish Homebrew Release

on:
  workflow_run:
    workflows: ["Build and Upload .NET binary"]
    types:
      - completed

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: mislav/bump-homebrew-formula-action@v4
        name: Bump Homebrew formula
        with:
          formula-name: busly-cli
          homebrew-tap: tragiccode/homebrew-tap-busly-cli
          tag-name: ${{ github.event.workflow_run.head_branch }}
          download-url: https://github.com/TraGicCode/busly-cli/releases/download/${{ github.event.workflow_run.head_branch }}/busly-cli-${{ github.event.workflow_run.head_branch }}-osx-arm64.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.GH_TOKEN_FOR_HOMEBREW_PUBLISH }}
