name: Publish WinGet Release

on:
  workflow_run:
    workflows: ["Build and Upload .NET binary"]
    types: [completed]

jobs:
  build-and-pack:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Sync winget-pkgs fork
        run: gh repo sync TraGicCode/winget-pkgs -b master --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Winget package
        uses: michidk/winget-updater@v1
        with:
          komac-token: ${{ secrets.GH_TOKEN_FOR_WINGET_PUBLISH }}
          identifier: "TragicCode.BuslyCLI"
          repo: "TraGicCode/busly-cli"
          url: "https://github.com/TraGicCode/busly-cli/releases/download/${{ github.event.workflow_run.head_branch }}/busly-cli-${{ github.event.workflow_run.head_branch }}-win-x64.zip"
